global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      # Adjust to the homelab-network IP address (since node_exporter is running in the host network mode)
      - targets: ["172.18.0.1:9100"]

  - job_name: "smartctl"
    static_configs:
      # Container name is enough since prometheus and smartctl-exporter are in the same network
      - targets: ["smartctl-exporter:9633"]
